version: '2'
services:
  web:
    image: shravan6488/hello-ebot7:ebot7
  nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    ports:
      - 8080:80
      - 8090:8090
    environment:
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=ebot7
      - PROXY_PASS=http://web/
