version: '2'
services:
  web:
    image: shravan6488/hello-ebot7:latest
  nginx:
    image: quay.io/shravan6488/nginx-helloebot-auth:latest
    ports:
      - 8080:80
      - 8090:8090
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - PROXY_PASS=http://web/
